// lib/mock-data.ts
// Realistic seed data and local state management for Letenent Coaching OS

import { TraineeProfile, Exercise, WorkoutLog, CheckIn, User, ActivityItem } from '@/types';

export const CURRENT_COACH: User = {
  id: 'usr_coach_01',
  name: 'Roger Bothman',
  email: 'roger@letenent.io',
  role: 'COACH',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  createdAt: '2024-01-10T00:00:00Z',
  updatedAt: '2024-01-10T00:00:00Z',
};

export const INITIAL_EXERCISES: Exercise[] = [
  { id: 'ex_1', name: 'Barbell Back Squat', muscleGroup: 'Quads & Glutes', equipment: 'Barbell, Squat Rack' },
  { id: 'ex_2', name: 'Romanian Deadlift (RDL)', muscleGroup: 'Hamstrings & Glutes', equipment: 'Barbell' },
  { id: 'ex_3', name: 'Incline Dumbbell Bench Press', muscleGroup: 'Upper Chest & Front Delts', equipment: 'Adjustable Bench, Dumbbells' },
  { id: 'ex_4', name: 'Neutral Grip Lat Pulldown', muscleGroup: 'Lats & Upper Back', equipment: 'Cable Pulldown Station' },
  { id: 'ex_5', name: 'Barbell Overhead Press', muscleGroup: 'Shoulders & Triceps', equipment: 'Barbell' },
  { id: 'ex_6', name: 'Bulgarian Split Squat', muscleGroup: 'Quads & Glutes', equipment: 'Dumbbells, Bench' },
  { id: 'ex_7', name: 'Cable Lateral Raise', muscleGroup: 'Lateral Deltoids', equipment: 'Cable Station' },
  { id: 'ex_8', name: 'Chest-Supported Row', muscleGroup: 'Mid-Back & Rhomboids', equipment: 'Incline Bench, Dumbbells' },
  { id: 'ex_9', name: 'Incline Hammer Curl', muscleGroup: 'Biceps & Brachialis', equipment: 'Dumbbells, Bench' },
  { id: 'ex_10', name: 'Hanging Leg Raise', muscleGroup: 'Core & Hip Flexors', equipment: 'Pull-Up Bar' },
];

export const INITIAL_TRAINEES: TraineeProfile[] = [
  {
    id: 'trainee_kaiya',
    userId: 'usr_t_kaiya',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-03-01T00:00:00Z',
    targetFocus: 'Push Strength & Upper Body Hypertrophy',
    compliance14Days: 96,
    workoutsAssigned14Days: 12,
    workoutsCompleted14Days: 12,
    user: {
      id: 'usr_t_kaiya',
      name: 'Kaiya',
      email: 'kaiya@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-03-01T00:00:00Z',
      updatedAt: '2024-03-01T00:00:00Z',
    },
  },
  {
    id: 'trainee_wilson',
    userId: 'usr_t_wilson',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-02-15T00:00:00Z',
    targetFocus: 'Pull Day & Posterior Chain Volume',
    compliance14Days: 92,
    workoutsAssigned14Days: 12,
    workoutsCompleted14Days: 11,
    user: {
      id: 'usr_t_wilson',
      name: 'Wilson',
      email: 'wilson@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-02-15T00:00:00Z',
      updatedAt: '2024-02-15T00:00:00Z',
    },
  },
  {
    id: 'trainee_olivia',
    userId: 'usr_t_olivia',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-04-01T00:00:00Z',
    targetFocus: 'Hypertrophy & Bench Volume',
    compliance14Days: 91,
    workoutsAssigned14Days: 11,
    workoutsCompleted14Days: 10,
    user: {
      id: 'usr_t_olivia',
      name: 'Olivia',
      email: 'olivia@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-04-01T00:00:00Z',
      updatedAt: '2024-04-01T00:00:00Z',
    },
  },
  {
    id: 'trainee_01',
    userId: 'usr_t_01',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-02-01T00:00:00Z',
    targetFocus: 'Hypertrophy & Strength (Powerbuilding Block)',
    compliance14Days: 92,
    workoutsAssigned14Days: 12,
    workoutsCompleted14Days: 11,
    user: {
      id: 'usr_t_01',
      name: 'Marcus Chen',
      email: 'marcus.chen@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-02-01T00:00:00Z',
      updatedAt: '2024-02-01T00:00:00Z',
    },
  },
  {
    id: 'trainee_02',
    userId: 'usr_t_02',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-03-15T00:00:00Z',
    targetFocus: 'Functional Hypertrophy & Athletic Endurance',
    compliance14Days: 83,
    workoutsAssigned14Days: 12,
    workoutsCompleted14Days: 10,
    user: {
      id: 'usr_t_02',
      name: 'Sarah Jenkins',
      email: 's.jenkins@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-03-15T00:00:00Z',
      updatedAt: '2024-03-15T00:00:00Z',
    },
  },
  {
    id: 'trainee_05',
    userId: 'usr_t_05',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-04-10T00:00:00Z',
    targetFocus: 'Powerlifting Prep (Squat & Deadlift Peak)',
    compliance14Days: 95,
    workoutsAssigned14Days: 12,
    workoutsCompleted14Days: 12,
    user: {
      id: 'usr_t_05',
      name: 'Liam Brooks',
      email: 'liam.brooks@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-04-10T00:00:00Z',
      updatedAt: '2024-04-10T00:00:00Z',
    },
  },
  {
    id: 'trainee_06',
    userId: 'usr_t_06',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-05-20T00:00:00Z',
    targetFocus: 'Speed-Strength & Rotational Power',
    compliance14Days: 88,
    workoutsAssigned14Days: 10,
    workoutsCompleted14Days: 9,
    user: {
      id: 'usr_t_06',
      name: 'Sophia Torres',
      email: 'sophia.t@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-05-20T00:00:00Z',
      updatedAt: '2024-05-20T00:00:00Z',
    },
  },
  {
    id: 'trainee_07',
    userId: 'usr_t_07',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-06-01T00:00:00Z',
    targetFocus: 'Upper Body Bodybuilding Split',
    compliance14Days: 85,
    workoutsAssigned14Days: 10,
    workoutsCompleted14Days: 8,
    user: {
      id: 'usr_t_07',
      name: 'Lucas Graham',
      email: 'lucas.g@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-06-01T00:00:00Z',
      updatedAt: '2024-06-01T00:00:00Z',
    },
  },
  {
    id: 'trainee_08',
    userId: 'usr_t_08',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-06-15T00:00:00Z',
    targetFocus: 'Glute & Hamstring Specialization',
    compliance14Days: 90,
    workoutsAssigned14Days: 10,
    workoutsCompleted14Days: 9,
    user: {
      id: 'usr_t_08',
      name: 'Maya Lin',
      email: 'maya.lin@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-06-15T00:00:00Z',
      updatedAt: '2024-06-15T00:00:00Z',
    },
  },
  {
    id: 'trainee_09',
    userId: 'usr_t_09',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-07-01T00:00:00Z',
    targetFocus: 'Athletic Conditioning & Hypertrophy',
    compliance14Days: 87,
    workoutsAssigned14Days: 8,
    workoutsCompleted14Days: 7,
    user: {
      id: 'usr_t_09',
      name: 'Jordan Reed',
      email: 'jordan.r@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-07-01T00:00:00Z',
      updatedAt: '2024-07-01T00:00:00Z',
    },
  },
  {
    id: 'trainee_10',
    userId: 'usr_t_10',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-07-10T00:00:00Z',
    targetFocus: 'Mobility & Hypertrophy Foundation',
    compliance14Days: 89,
    workoutsAssigned14Days: 9,
    workoutsCompleted14Days: 8,
    user: {
      id: 'usr_t_10',
      name: 'Chloe Bennett',
      email: 'chloe.b@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-07-10T00:00:00Z',
      updatedAt: '2024-07-10T00:00:00Z',
    },
  },
  {
    id: 'trainee_11',
    userId: 'usr_t_11',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-08-01T00:00:00Z',
    targetFocus: 'Strength & Deadlift Specialization',
    compliance14Days: 94,
    workoutsAssigned14Days: 10,
    workoutsCompleted14Days: 9,
    user: {
      id: 'usr_t_11',
      name: 'Daniel Kim',
      email: 'daniel.k@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-08-01T00:00:00Z',
      updatedAt: '2024-08-01T00:00:00Z',
    },
  },
  {
    id: 'trainee_12',
    userId: 'usr_t_12',
    coachId: 'coach_prof_01',
    status: 'ACTIVE',
    joinedAt: '2024-08-15T00:00:00Z',
    targetFocus: 'Cross-Training & Functional Mass',
    compliance14Days: 86,
    workoutsAssigned14Days: 8,
    workoutsCompleted14Days: 7,
    user: {
      id: 'usr_t_12',
      name: 'Tyler Brooks',
      email: 'tyler.b@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-08-15T00:00:00Z',
      updatedAt: '2024-08-15T00:00:00Z',
    },
  },
  // 3 Inactive / Past 7 Days Inactive Trainees
  {
    id: 'trainee_tom',
    userId: 'usr_t_tom',
    coachId: 'coach_prof_01',
    status: 'PAUSED',
    joinedAt: '2024-01-20T00:00:00Z',
    targetFocus: 'Body Recomposition & Measurement Tracking',
    compliance14Days: 45,
    workoutsAssigned14Days: 6,
    workoutsCompleted14Days: 2,
    user: {
      id: 'usr_t_tom',
      name: 'Tom',
      email: 'tom@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-01-20T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
  },
  {
    id: 'trainee_benjamin',
    userId: 'usr_t_benjamin',
    coachId: 'coach_prof_01',
    status: 'INVITED',
    onboardingToken: 'ltnt_benjamin_token',
    joinedAt: '2024-09-15T00:00:00Z',
    targetFocus: 'Invitation Accepted (Onboarding Routine)',
    compliance14Days: 0,
    workoutsAssigned14Days: 0,
    workoutsCompleted14Days: 0,
    user: {
      id: 'usr_t_benjamin',
      name: 'Benjamin',
      email: 'benjamin@example.com',
      role: 'TRAINEE',
      avatarUrl: undefined, // Will render BK initial badge
      createdAt: '2024-09-15T00:00:00Z',
      updatedAt: '2024-09-15T00:00:00Z',
    },
  },
  {
    id: 'trainee_03',
    userId: 'usr_t_03',
    coachId: 'coach_prof_01',
    status: 'INVITED',
    onboardingToken: 'ltnt_e982a17f8b924719c8d10b7e289f64a1',
    joinedAt: '2024-09-12T00:00:00Z',
    targetFocus: 'Olympic Weightlifting Technique & Mobility',
    compliance14Days: 0,
    workoutsAssigned14Days: 0,
    workoutsCompleted14Days: 0,
    user: {
      id: 'usr_t_03',
      name: 'Elena Rostova',
      email: 'elena.rostova@example.com',
      role: 'TRAINEE',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      createdAt: '2024-09-12T00:00:00Z',
      updatedAt: '2024-09-12T00:00:00Z',
    },
  },
];

export const INITIAL_TODAY_WORKOUT: WorkoutLog = {
  id: 'wlog_today_01',
  traineeId: 'trainee_01',
  assignedWorkoutId: 'asw_01',
  workoutTitle: 'Day 1: Upper Body Power & Hypertrophy Focus',
  startedAt: new Date().toISOString(),
  status: 'IN_PROGRESS',
  sets: [
    // Incline DB Bench Press
    {
      id: 'set_1',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_3',
      exerciseName: 'Incline Dumbbell Bench Press',
      setNumber: 1,
      targetReps: '8-10',
      targetLoad: 75,
      actualReps: 10,
      actualLoad: 75,
      rpe: 8,
      completed: true,
      completedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: 'set_2',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_3',
      exerciseName: 'Incline Dumbbell Bench Press',
      setNumber: 2,
      targetReps: '8-10',
      targetLoad: 75,
      actualReps: 9,
      actualLoad: 75,
      rpe: 8.5,
      completed: true,
      completedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    {
      id: 'set_3',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_3',
      exerciseName: 'Incline Dumbbell Bench Press',
      setNumber: 3,
      targetReps: '8-10',
      targetLoad: 75,
      actualReps: 8,
      actualLoad: 75,
      rpe: 9,
      completed: false,
    },
    // Neutral Grip Lat Pulldown
    {
      id: 'set_4',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_4',
      exerciseName: 'Neutral Grip Lat Pulldown',
      setNumber: 1,
      targetReps: '10-12',
      targetLoad: 150,
      actualReps: 12,
      actualLoad: 150,
      rpe: 8,
      completed: false,
    },
    {
      id: 'set_5',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_4',
      exerciseName: 'Neutral Grip Lat Pulldown',
      setNumber: 2,
      targetReps: '10-12',
      targetLoad: 150,
      actualReps: 11,
      actualLoad: 150,
      rpe: 8.5,
      completed: false,
    },
    {
      id: 'set_6',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_4',
      exerciseName: 'Neutral Grip Lat Pulldown',
      setNumber: 3,
      targetReps: '10-12',
      targetLoad: 150,
      actualReps: 10,
      actualLoad: 150,
      rpe: 9,
      completed: false,
    },
    // Barbell Overhead Press
    {
      id: 'set_7',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_5',
      exerciseName: 'Barbell Overhead Press',
      setNumber: 1,
      targetReps: '6-8',
      targetLoad: 115,
      actualReps: 8,
      actualLoad: 115,
      rpe: 8,
      completed: false,
    },
    {
      id: 'set_8',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_5',
      exerciseName: 'Barbell Overhead Press',
      setNumber: 2,
      targetReps: '6-8',
      targetLoad: 115,
      actualReps: 7,
      actualLoad: 115,
      rpe: 8.5,
      completed: false,
    },
    // Cable Lateral Raise
    {
      id: 'set_9',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_7',
      exerciseName: 'Cable Lateral Raise',
      setNumber: 1,
      targetReps: '12-15',
      targetLoad: 25,
      actualReps: 15,
      actualLoad: 25,
      rpe: 8.5,
      completed: false,
    },
    {
      id: 'set_10',
      workoutLogId: 'wlog_today_01',
      exerciseId: 'ex_7',
      exerciseName: 'Cable Lateral Raise',
      setNumber: 2,
      targetReps: '12-15',
      targetLoad: 25,
      actualReps: 14,
      actualLoad: 25,
      rpe: 9,
      completed: false,
    },
  ],
};

export const INITIAL_CHECK_INS: CheckIn[] = [
  {
    id: 'chk_01',
    traineeId: 'trainee_02',
    traineeName: 'Sarah Jenkins',
    submittedAt: '2024-09-15T08:30:00Z',
    morningWeightLbs: 138.4,
    energyScore: 8,
    stressScore: 4,
    sleepScore: 9,
    dietAdherenceScore: 8,
    wins: 'Hit an all-time RDL triple at 205 lbs feeling completely locked in and zero low-back fatigue. Morning energy has been noticeably higher.',
    struggles: 'Had to move Thursday workout to Saturday due to work travel; had minor difficulty hitting protein target on travel day (missed by ~20g).',
    status: 'PENDING_REVIEW',
    complianceStats: {
      workoutsCompleted: 10,
      workoutsAssigned: 12,
      compliancePercent: 83,
    },
  },
  {
    id: 'chk_02',
    traineeId: 'trainee_01',
    traineeName: 'Marcus Chen',
    submittedAt: '2024-09-08T09:15:00Z',
    morningWeightLbs: 182.2,
    energyScore: 9,
    stressScore: 5,
    sleepScore: 8,
    dietAdherenceScore: 9,
    wins: 'Crushed bench sets at 245 lbs. Shoulder mobility warm-up protocol is paying massive dividends.',
    struggles: 'Grip fatigue on heavy barbell row sets.',
    status: 'REVIEWED',
    coachFeedback: 'Outstanding execution Marcus! The bench bar speed looked phenomenal on the video clip. For the rows, feel free to use figure-8 straps so grip never caps your lat recruitment.',
    reviewedAt: '2024-09-08T14:20:00Z',
    complianceStats: {
      workoutsCompleted: 11,
      workoutsAssigned: 12,
      compliancePercent: 92,
    },
  },
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act_kaiya_01',
    type: 'WORKOUT_COMPLETED',
    traineeId: 'trainee_kaiya',
    traineeName: 'Kaiya',
    traineeAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    title: 'Completed Push Day Workout',
    description: 'She lifted 7,800 kg over 23 sets.',
    workoutDuration: '56-minute',
    workoutName: 'Push Day',
    weightLiftedKg: 7800,
    setsCount: 23,
    timestamp: '3 hours ago',
    metrics: [
      { label: 'Volume', value: '7,800 kg' },
      { label: 'Sets', value: '23 sets' },
      { label: 'Duration', value: '56 min' },
    ],
  },
  {
    id: 'act_wilson_01',
    type: 'WORKOUT_COMPLETED',
    traineeId: 'trainee_wilson',
    traineeName: 'Wilson',
    traineeAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    title: 'Completed Pull Day Workout',
    description: 'He lifted 8,568 kg over 23 sets.',
    workoutDuration: '58-minute',
    workoutName: 'Pull Day',
    weightLiftedKg: 8568,
    setsCount: 23,
    exercisesList: [
      'Bench Press (Barbell)',
      'Arnold Press (Dumbbell)',
      'Bench Press (Machine)',
    ],
    timestamp: '5 hours ago',
    metrics: [
      { label: 'Volume', value: '8,568 kg' },
      { label: 'Sets', value: '23 sets' },
      { label: 'Duration', value: '58 min' },
    ],
  },
  {
    id: 'act_tom_01',
    type: 'CHECK_IN_SUBMITTED',
    traineeId: 'trainee_tom',
    traineeName: 'Tom',
    traineeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Measurement Added',
    description: 'A new weight of 78 kg has been added to the measurements of Tom, which is 2 kg more than last time.',
    measurementText: 'A new weight of 78 kg has been added to the measurements of Tom, which is 2 kg more than last time.',
    timestamp: '5 hours ago',
    metrics: [
      { label: 'Weight', value: '78 kg' },
      { label: 'Delta', value: '+2 kg' },
    ],
  },
  {
    id: 'act_benjamin_01',
    type: 'PROGRAM_ASSIGNED',
    traineeId: 'trainee_benjamin',
    traineeName: 'Benjamin',
    avatarInitials: 'BK',
    isInvitationAccepted: true,
    title: 'Invitation Accepted',
    description: 'Benjamin has accepted your coaching invitation.',
    timestamp: '6 hours ago',
    metrics: [
      { label: 'Status', value: 'Active Roster' },
      { label: 'Action', value: 'Invite Accepted' },
    ],
  },
  {
    id: 'act_olivia_01',
    type: 'WORKOUT_COMPLETED',
    traineeId: 'trainee_olivia',
    traineeName: 'Olivia',
    traineeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    title: 'Completed Push Day Workout',
    description: 'She lifted 7,800 kg over 23 sets.',
    workoutDuration: '56-minute',
    workoutName: 'Push Day',
    weightLiftedKg: 7800,
    setsCount: 23,
    timestamp: '8 hours ago',
    metrics: [
      { label: 'Volume', value: '7,800 kg' },
      { label: 'Sets', value: '23 sets' },
      { label: 'Duration', value: '56 min' },
    ],
  },
  {
    id: 'act_01',
    type: 'WORKOUT_COMPLETED',
    traineeId: 'trainee_01',
    traineeName: 'Marcus Chen',
    traineeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Completed Day 1: Upper Body Power',
    description: 'Finished all 10 prescribed sets with strict rest periods. Reported sharp bar speed on Incline Dumbbell Presses.',
    timestamp: 'Yesterday',
    metrics: [
      { label: 'Sets Logged', value: '10 / 10' },
      { label: 'Top Load', value: '75 lbs DBs' },
      { label: 'Session RPE', value: '8.5' },
    ],
  },
  {
    id: 'act_02',
    type: 'CHECK_IN_SUBMITTED',
    traineeId: 'trainee_02',
    traineeName: 'Sarah Jenkins',
    traineeAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    title: 'Submitted Weekly Check-In (Week 3)',
    description: 'Fasted weigh-in 138.4 lbs (-1.2 lbs vs baseline). Energy 8/10, Sleep 9/10. Ready for coach feedback.',
    timestamp: 'Yesterday',
    metrics: [
      { label: 'Morning Weight', value: '138.4 lbs' },
      { label: 'Energy / Sleep', value: '8 / 9' },
    ],
  },
];

export interface WeeklyActivePoint {
  id: string;
  dateLabel: string;
  showAxisLabel: boolean;
  activeCount: number;
}

export const INITIAL_WEEKLY_ACTIVE: WeeklyActivePoint[] = [
  { id: 'w1', dateLabel: 'May 22', showAxisLabel: true, activeCount: 3.5 },
  { id: 'w2', dateLabel: 'May 29', showAxisLabel: false, activeCount: 3.5 },
  { id: 'w3', dateLabel: 'Jun 5', showAxisLabel: true, activeCount: 1.2 },
  { id: 'w4', dateLabel: 'Jun 12', showAxisLabel: false, activeCount: 2.2 },
  { id: 'w5', dateLabel: 'Jun 19', showAxisLabel: true, activeCount: 4.8 },
  { id: 'w6', dateLabel: 'Jun 26', showAxisLabel: false, activeCount: 4.8 },
  { id: 'w7', dateLabel: 'Jul 3', showAxisLabel: true, activeCount: 13.2 },
  { id: 'w8', dateLabel: 'Jul 10', showAxisLabel: false, activeCount: 10.8 },
  { id: 'w9', dateLabel: 'Jul 17', showAxisLabel: true, activeCount: 6.0 },
  { id: 'w10', dateLabel: 'Jul 24', showAxisLabel: false, activeCount: 11.0 },
  { id: 'w11', dateLabel: 'Jul 31', showAxisLabel: true, activeCount: 11.4 },
  { id: 'w12', dateLabel: 'Aug 7', showAxisLabel: false, activeCount: 13.2 },
];
